#!/usr/bin/env python3
"""Remove accounts created by automated tests, and everything they own.

Why this exists: the merchandising features read real tables. "Trending this week"
and the "Bestseller" badge are computed from `order_items`, so a load test that
bought 200 copies of one title makes that title the shop's headline recommendation.
Test accounts are not a tidiness problem, they are wrong output on the storefront.

Dry run by default. It reports what it would delete and changes nothing:

  PYTHONPATH=. ./venv/bin/python scripts/purge_test_data.py
  PYTHONPATH=. ./venv/bin/python scripts/purge_test_data.py --apply

Accounts are matched by e-mail pattern. `KEEP` is checked first and always wins, so
the real admin and demo logins cannot be caught by a pattern. Orders, cart items,
wishlists, reviews, notifications and refresh tokens go with the user via
`ON DELETE CASCADE`; `order_items.book_id` is `RESTRICT`, which only protects books,
not the order rows themselves.

Books are never touched: deleting an order does not restore its stock, so the
counts stay as they are. If you want the stock back, cancel the orders through the
API first — that path restores it properly.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from sqlalchemy import text  # noqa: E402

from app.core.config import settings  # noqa: E402
from app.database.db import SessionLocal  # noqa: E402

# Never delete these, whatever the patterns say.
KEEP = {"admin@booknest.com", "demo@booknest.com"}

# Generated by the various test and verification runs in this project.
PATTERNS = [
    ("racer%@booknest.com", "concurrency/load test"),
    ("e2e-%@booknest.com", "API verification"),
    ("uicheck%@booknest.com", "browser verification"),
    ("cust-%@booknest.com", "pytest fixtures"),
    # Timestamped throwaway accounts from browser runs, e.g. buyer1787122099@bookvuk.com.
    ("guest%@bookvuk.com", "browser verification"),
    ("buyer%@bookvuk.com", "browser verification"),
    ("flow%@bookvuk.com", "browser verification"),
    ("cart%@bookvuk.com", "browser verification"),
    ("gf%@bookvuk.com", "browser verification"),
    ("prof%@bookvuk.com", "browser verification"),
    ("pui%@bookvuk.com", "browser verification"),
    ("w2%@bookvuk.com", "browser verification"),
]


# Only notifications that name an order, and only where that order is gone. The
# `%-%-%` guard keeps this away from messages that mention no id at all (a low-stock
# alert, say), so it can never widen into "delete anything unmatched".
ORPHANED_NOTIFICATIONS_SQL = """
DELETE FROM notifications n
WHERE n.body ~ '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  AND NOT EXISTS (
    SELECT 1 FROM orders o WHERE position(o.id::text IN n.body) > 0
  )
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Purge automated-test accounts")
    parser.add_argument("--apply", action="store_true",
                        help="actually delete (default is a dry run)")
    args = parser.parse_args()

    print(f"database: {settings.safe_database_target}")
    print(f"mode:     {'APPLY — deletes rows' if args.apply else 'dry run — no changes'}\n")

    session = SessionLocal()
    try:
        keep_list = list(KEEP)
        victims: list[tuple[str, str]] = []
        for pattern, reason in PATTERNS:
            rows = session.execute(
                text("SELECT email FROM users WHERE email LIKE :p AND email <> ALL(:keep)"),
                {"p": pattern, "keep": keep_list},
            ).fetchall()
            victims.extend((r[0], reason) for r in rows)

        # A pattern can match the same account twice; delete each once.
        seen: dict[str, str] = {}
        for email, reason in victims:
            seen.setdefault(email, reason)

        emails = list(seen)

        if seen:
            counts = session.execute(
                text("""SELECT
                          (SELECT count(*) FROM orders o JOIN users u ON u.id = o.user_id
                            WHERE u.email = ANY(:e)) AS orders,
                          (SELECT coalesce(sum(oi.quantity), 0) FROM order_items oi
                            JOIN orders o ON o.id = oi.order_id
                            JOIN users u ON u.id = o.user_id WHERE u.email = ANY(:e)) AS units,
                          (SELECT count(*) FROM reviews r JOIN users u ON u.id = r.user_id
                            WHERE u.email = ANY(:e)) AS reviews"""),
                {"e": emails},
            ).first()

            print(f"{len(seen)} test accounts, {counts.orders} orders, "
                  f"{counts.units} units sold, {counts.reviews} reviews:")
            for email, reason in sorted(seen.items()):
                print(f"  {email:40} ({reason})")
            print("\nkeeping:", ", ".join(sorted(KEEP)))
        else:
            print("No test accounts found.")

        # Counted the same way it is deleted, so the dry run cannot understate it.
        # Checked whether or not any accounts matched: a previous run may have
        # removed the orders and left these behind, which is exactly what happened
        # the first time this script ran.
        orphan_count = session.execute(
            text("SELECT count(*) FROM notifications n WHERE n.body ~ "
                 "'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' "
                 "AND NOT EXISTS (SELECT 1 FROM orders o "
                 "WHERE position(o.id::text IN n.body) > 0)")
        ).scalar()
        print(f"\n{orphan_count} notifications point at an order that no longer exists")

        if not seen and not orphan_count:
            print("Nothing to do.")
            return 0

        if not args.apply:
            print("\nDry run — nothing deleted. Re-run with --apply to remove these.")
            return 0

        deleted = 0
        if emails:
            deleted = session.execute(
                text("DELETE FROM users WHERE email = ANY(:e)"), {"e": emails}
            ).rowcount

        # A customer's own notifications cascade with them. The *admin's* do not:
        # "New order placed" and "Refund needed" belong to the admin, and reference
        # their order only as an id inside the message text, so there is no foreign
        # key to cascade along. Left alone they become bell entries pointing at
        # orders that no longer exist.
        orphaned = session.execute(text(ORPHANED_NOTIFICATIONS_SQL)).rowcount

        session.commit()
        print(f"\ndeleted {deleted} accounts and everything cascading from them")
        print(f"deleted {orphaned} notifications that referenced a now-deleted order")
        print("Note: book stock is unchanged — deleting an order does not restore it.")
        return 0
    finally:
        session.close()


if __name__ == "__main__":
    raise SystemExit(main())
