/** 100 popular English titles in India: fiction, non-fiction, business, self-help, history, sci-fi, tech. */
const englishTitles = [
  ["Five Point Someone", "Chetan Bhagat", "Fiction"],
  ["One Night @ the Call Center", "Chetan Bhagat", "Fiction"],
  ["The 3 Mistakes of My Life", "Chetan Bhagat", "Fiction"],
  ["2 States", "Chetan Bhagat", "Fiction"],
  ["Revolution 2020", "Chetan Bhagat", "Fiction"],
  ["Half Girlfriend", "Chetan Bhagat", "Fiction"],
  ["One Indian Girl", "Chetan Bhagat", "Fiction"],
  ["The Immortals of Meluha", "Amish Tripathi", "Fiction"],
  ["The Secret of the Nagas", "Amish Tripathi", "Fiction"],
  ["The Oath of the Vayuputras", "Amish Tripathi", "Fiction"],
  ["Scion of Ikshvaku", "Amish Tripathi", "Fiction"],
  ["Sita: Warrior of Mithila", "Amish Tripathi", "Fiction"],
  ["Raavan: Enemy of Aryavarta", "Amish Tripathi", "Fiction"],
  ["The White Tiger", "Aravind Adiga", "Fiction"],
  ["Between the Assassinations", "Aravind Adiga", "Fiction"],
  ["Last Man in Tower", "Aravind Adiga", "Fiction"],
  ["The God of Small Things", "Arundhati Roy", "Fiction"],
  ["The Ministry of Utmost Happiness", "Arundhati Roy", "Fiction"],
  ["A Suitable Boy", "Vikram Seth", "Fiction"],
  ["An Equal Music", "Vikram Seth", "Fiction"],
  ["Two Lives", "Vikram Seth", "Fiction"],
  ["Midnight's Children", "Salman Rushdie", "Fiction"],
  ["Shame", "Salman Rushdie", "Fiction"],
  ["The Satanic Verses", "Salman Rushdie", "Fiction"],
  ["Interpreter of Maladies", "Jhumpa Lahiri", "Fiction"],
  ["The Namesake", "Jhumpa Lahiri", "Fiction"],
  ["Unaccustomed Earth", "Jhumpa Lahiri", "Fiction"],
  ["The Lowland", "Jhumpa Lahiri", "Fiction"],
  ["Train to Pakistan", "Khushwant Singh", "Fiction"],
  ["I Shall Not Hear the Nightingale", "Khushwant Singh", "Fiction"],
  ["The Company of Women", "Khushwant Singh", "Fiction"],
  ["The Inheritance of Loss", "Kiran Desai", "Fiction"],
  ["Hullabaloo in the Guava Orchard", "Kiran Desai", "Fiction"],
  ["The Great Indian Novel", "Shashi Tharoor", "Fiction"],
  ["Riot", "Shashi Tharoor", "Fiction"],
  ["Show Business", "Shashi Tharoor", "Fiction"],
  ["Sacred Games", "Vikram Chandra", "Fiction"],
  ["Red Earth and Pouring Rain", "Vikram Chandra", "Fiction"],
  ["A Fine Balance", "Rohinton Mistry", "Fiction"],
  ["Family Matters", "Rohinton Mistry", "Fiction"],
  ["Such a Long Journey", "Rohinton Mistry", "Fiction"],
  ["The Guide", "R. K. Narayan", "Fiction"],
  ["Malgudi Days", "R. K. Narayan", "Fiction"],
  ["The English Teacher", "R. K. Narayan", "Fiction"],
  ["Swami and Friends", "R. K. Narayan", "Fiction"],
  ["The Bachelor of Arts", "R. K. Narayan", "Fiction"],
  ["Untouchable", "Mulk Raj Anand", "Fiction"],
  ["Coolie", "Mulk Raj Anand", "Fiction"],
  ["Private Life of an Indian Prince", "Mulk Raj Anand", "Fiction"],
  ["The Room on the Roof", "Ruskin Bond", "Fiction"],
  ["The Blue Umbrella", "Ruskin Bond", "Fiction"],
  ["A Flight of Pigeons", "Ruskin Bond", "Fiction"],
  ["Ignited Minds", "A. P. J. Abdul Kalam", "Self growth"],
  ["Wings of Fire", "A. P. J. Abdul Kalam", "Self growth"],
  ["India 2020", "A. P. J. Abdul Kalam", "Self growth"],
  ["The Story of My Experiments with Truth", "M. K. Gandhi", "History"],
  ["The Discovery of India", "Jawaharlal Nehru", "History"],
  ["India Wins Freedom", "Maulana Abul Kalam Azad", "History"],
  ["The Argumentative Indian", "Amartya Sen", "History"],
  ["The Idea of Justice", "Amartya Sen", "History"],
  ["Playing It My Way", "Sachin Tendulkar", "History"],
  ["Atomic Habits", "James Clear", "Self growth"],
  ["Ikigai", "Héctor García", "Self growth"],
  ["The Alchemist", "Paulo Coelho", "Fiction"],
  ["Think and Grow Rich", "Napoleon Hill", "Self growth"],
  ["Rich Dad Poor Dad", "Robert Kiyosaki", "Business"],
  ["The Psychology of Money", "Morgan Housel", "Business"],
  ["Sapiens", "Yuval Noah Harari", "History"],
  ["Homo Deus", "Yuval Noah Harari", "History"],
  ["21 Lessons for the 21st Century", "Yuval Noah Harari", "History"],
  ["Educated", "Tara Westover", "Fiction"],
  ["Becoming", "Michelle Obama", "History"],
  ["The Subtle Art of Not Giving a F*ck", "Mark Manson", "Self growth"],
  ["Can't Hurt Me", "David Goggins", "Self growth"],
  ["Deep Work", "Cal Newport", "Self growth"],
  ["The Power of Now", "Eckhart Tolle", "Self growth"],
  ["The 7 Habits of Highly Effective People", "Stephen Covey", "Self growth"],
  ["How to Win Friends and Influence People", "Dale Carnegie", "Self growth"],
  ["Start With Why", "Simon Sinek", "Business"],
  ["Good to Great", "Jim Collins", "Business"],
  ["The Lean Startup", "Eric Ries", "Business"],
  ["Zero to One", "Peter Thiel", "Business"],
  ["The Hard Thing About Hard Things", "Ben Horowitz", "Business"],
  ["Shoe Dog", "Phil Knight", "Business"],
  ["Elon Musk", "Walter Isaacson", "History"],
  ["Steve Jobs", "Walter Isaacson", "History"],
  ["The Everything Store", "Brad Stone", "Business"],
  ["Bad Blood", "John Carreyrou", "Business"],
  ["Thinking, Fast and Slow", "Daniel Kahneman", "Business"],
  ["Freakonomics", "Steven Levitt", "Business"],
  ["Outliers", "Malcolm Gladwell", "Self growth"],
  ["The Code Breaker", "Walter Isaacson", "History"],
  ["Dune", "Frank Herbert", "Sci-fi"],
  ["Foundation", "Isaac Asimov", "Sci-fi"],
  ["Project Hail Mary", "Andy Weir", "Sci-fi"],
  ["The Hitchhiker's Guide to the Galaxy", "Douglas Adams", "Sci-fi"],
  ["Ender's Game", "Orson Scott Card", "Sci-fi"],
  ["The Three-Body Problem", "Liu Cixin", "Sci-fi"],
  ["Clean Code", "Robert C. Martin", "Technology"],
  ["The Pragmatic Programmer", "David Thomas", "Technology"]
];

export default englishTitles;
