/**
 * 100 Hindi titles (display in Devanagari). titleSearch/authorSearch help Open Library cover lookup.
 */
export default [
  { t: "गोदान", a: "मुंशी प्रेमचंद", ts: "Godan", as: "Munshi Premchand" },
  { t: "निर्मला", a: "मुंशी प्रेमचंद", ts: "Nirmala", as: "Munshi Premchand" },
  { t: "कर्मभूमि", a: "मुंशी प्रेमचंद", ts: "Karmabhoomi", as: "Munshi Premchand" },
  { t: "गबन", a: "मुंशी प्रेमचंद", ts: "Gaban", as: "Munshi Premchand" },
  { t: "रंगभूमि", a: "मुंशी प्रेमचंद", ts: "Rangbhoomi", as: "Munshi Premchand" },
  { t: "मानसरोवर", a: "मुंशी प्रेमचंद", ts: "Mansarovar", as: "Munshi Premchand" },
  { t: "सेवा सदन", a: "मुंशी प्रेमचंद", ts: "Seva Sadan", as: "Munshi Premchand" },
  { t: "प्रतिज्ञा", a: "मुंशी प्रेमचंद", ts: "Pratigya", as: "Munshi Premchand" },
  { t: "प्रेमाश्रम", a: "मुंशी प्रेमचंद", ts: "Premashram", as: "Munshi Premchand" },
  { t: "कायाकल्प", a: "मुंशी प्रेमचंद", ts: "Kayakalp", as: "Munshi Premchand" },
  { t: "मधुशाला", a: "हरिवंश राय बच्चन", ts: "Madhushala", as: "Harivansh Rai Bachchan" },
  { t: "मधुबाला", a: "हरिवंश राय बच्चन", ts: "Madhubala", as: "Harivansh Rai Bachchan" },
  { t: "मधुकलश", a: "हरिवंश राय बच्चन", ts: "Madhukalash", as: "Harivansh Rai Bachchan" },
  { t: "रश्मिरथी", a: "रामधारी सिंह दिनकर", ts: "Rashmirathi", as: "Ramdhari Singh Dinkar" },
  { t: "उर्वशी", a: "रामधारी सिंह दिनकर", ts: "Urvashi", as: "Ramdhari Singh Dinkar" },
  { t: "हंस", a: "रामधारी सिंह दिनकर", ts: "Hans", as: "Ramdhari Singh Dinkar" },
  { t: "कुरुक्षेत्र", a: "रामधारी सिंह दिनकर", ts: "Kurukshetra", as: "Ramdhari Singh Dinkar" },
  { t: "नीरजा", a: "महादेवी वर्मा", ts: "Neerja", as: "Mahadevi Verma" },
  { t: "रश्मि", a: "महादेवी वर्मा", ts: "Rashmi", as: "Mahadevi Verma" },
  { t: "दीप", a: "महादेवी वर्मा", ts: "Deep", as: "Mahadevi Verma" },
  { t: "यामा", a: "महादेवी वर्मा", ts: "Yama", as: "Mahadevi Verma" },
  { t: "कामायणी", a: "जयशंकर प्रसाद", ts: "Kamayani", as: "Jaishankar Prasad" },
  { t: "स्कन्दगुप्त", a: "जयशंकर प्रसाद", ts: "Skandagupta", as: "Jaishankar Prasad" },
  { t: "ध्रुवस्वामिनी", a: "जयशंकर प्रसाद", ts: "Dhruvswamini", as: "Jaishankar Prasad" },
  { t: "आषाढ़ का एक दिन", a: "मोहन राकेश", ts: "Ashadh Ka Ek Din", as: "Mohan Rakesh" },
  { t: "लहरों के राजहंस", a: "मोहन राकेश", ts: "Lehron Ke Rajhans", as: "Mohan Rakesh" },
  { t: "आधे अधूरे", a: "मोहन राकेश", ts: "Aadhe Adhure", as: "Mohan Rakesh" },
  { t: "गुनाहों का देवता", a: "धर्मवीर भारती", ts: "Gunahon Ka Devta", as: "Dharamvir Bharati" },
  { t: "सूरज का सातवाँ घोड़ा", a: "धर्मवीर भारती", ts: "Suraj Ka Satvan Ghoda", as: "Dharamvir Bharati" },
  { t: "चिदंबरा", a: "सुमित्रानंदन पंत", ts: "Chidambara", as: "Sumitranandan Pant" },
  { t: "चित्रलेखा", a: "भगवतीचरण वर्मा", ts: "Chitralekha", as: "Bhagwati Charan Verma" },
  { t: "चन्द्रकांता", a: "देवकी नंदन खत्री", ts: "Chandrakanta", as: "Devaki Nandan Khatri" },
  { t: "चन्द्रकांता संतति", a: "देवकी नंदन खत्री", ts: "Chandrakanta Santati", as: "Devaki Nandan Khatri" },
  { t: "राग दरबारी", a: "श्रीलाल शुक्ल", ts: "Raag Darbari", as: "Shrilal Shukla" },
  { t: "नौकर की कमीज़", a: "श्रीलाल शुक्ल", ts: "Naukar Ki Kameez", as: "Shrilal Shukla" },
  { t: "महाभोज", a: "मन्नू भंडारी", ts: "Mahabhoj", as: "Mannu Bhandari" },
  { t: "पिंजर", a: "अमृता प्रीतम", ts: "Pinjar", as: "Amrita Pritam" },
  { t: "रसीदी टिकट", a: "अमृता प्रीतम", ts: "Rasidi Ticket", as: "Amrita Pritam" },
  { t: "तितली", a: "शिवानी", ts: "Titli", as: "Shivani" },
  { t: "आपका बंटी", a: "मन्नू भंडारी", ts: "Aapka Bunti", as: "Mannu Bhandari" },
  { t: "मैला आँचल", a: "फणीश्वर नाथ रेणु", ts: "Maila Anchal", as: "Phanishwar Nath Renu" },
  { t: "आधा गाँव", a: "राही मासूम रज़ा", ts: "Aadha Gaon", as: "Rahi Masoom Raza" },
  { t: "तमस", a: "भीष्म साहनी", ts: "Tamas", as: "Bhisham Sahni" },
  { t: "टूटी हुई कड़ियाँ", a: "भीष्म साहनी", ts: "Tooti Hui Kadiyan", as: "Bhisham Sahni" },
  { t: "कितने पाकिस्तान", a: "कमलेश्वर", ts: "Kitne Pakistan", as: "Kamleshwar" },
  { t: "पीली छतरी वाली लड़की", a: "उदय प्रकाश", ts: "Peeli Chhatri Wali Ladki", as: "Uday Prakash" },
  { t: "रेत समाधि", a: "गीतांजलि श्री", ts: "Ret Samadhi", as: "Geetanjali Shree" },
  { t: "ख़ैरियत बग़ैर ख़ैरियत", a: "अमरकांत", ts: "Khairiyat", as: "Amarkant" },
  { t: "हज़ारी बाग़ की बहार", a: "अमरकांत", ts: "Hazari Bagh Ki Bahar", as: "Amarkant" },
  { t: "दो लोग", a: "मन्नू भंडारी", ts: "Do Log", as: "Mannu Bhandari" },
  { t: "त्रिकोण", a: "मन्नू भंडारी", ts: "Trikon", as: "Mannu Bhandari" },
  { t: "बहुवचन", a: "मन्नू भंडारी", ts: "Bahuvachan", as: "Mannu Bhandari" },
  { t: "मैं तुम्हें फिर मिलूँगी", a: "अमृता प्रीतम", ts: "Main Tumhe Phir Milungi", as: "Amrita Pritam" },
  { t: "क़लम", a: "अमृता प्रीतम", ts: "Kalam", as: "Amrita Pritam" },
  { t: "यह दोस्ती", a: "अमृता प्रीतम", ts: "Yeh Dosti", as: "Amrita Pritam" },
  { t: "बस स्त्री का मन", a: "श्रीलाल शुक्ल", ts: "Bas Stri Ka Man", as: "Shrilal Shukla" },
  { t: "हिंदी साहित्य का इतिहास", a: "रामचंद्र शुक्ल", ts: "Hindi Sahitya Ka Itihas", as: "Ramchandra Shukla" },
  { t: "कबीर ग्रंथावली", a: "कबीर", ts: "Kabir Granthavali", as: "Kabir" },
  { t: "रहीम के दोहे", a: "अब्दुर रहीम", ts: "Rahim Ke Dohe", as: "Abdur Rahim" },
  { t: "बिहारी के दोहे", a: "बिहारी", ts: "Bihari Ke Dohe", as: "Bihari" },
  { t: "रामचरितमानस", a: "गोस्वामी तुलसीदास", ts: "Ramcharitmanas", as: "Tulsidas" },
  { t: "हनुमान चालीसा", a: "गोस्वामी तुलसीदास", ts: "Hanuman Chalisa", as: "Tulsidas" },
  { t: "भारत का संविधान", a: "डॉ. भीमराव अम्बेडकर", ts: "Constitution of India Hindi", as: "B R Ambedkar" },
  { t: "इतिहास के कुछ पन्ने", a: "जवाहरलाल नेहरू", ts: "Itihas Ke Kuch Panne", as: "Jawaharlal Nehru" },
  { t: "मेरी कहानी", a: "सुभाष चंद्र बोस", ts: "Meri Kahani", as: "Subhas Chandra Bose" },
  { t: "हिंदी नवजागरण", a: "हजारी प्रसाद द्विवेदी", ts: "Hindi Navjagaran", as: "Hazari Prasad Dwivedi" },
  { t: "नवलेखन", a: "नामवर सिंह", ts: "Navlekhan", as: "Namvar Singh" },
  { t: "दोहा", a: "सूरदास", ts: "Doha Surdas", as: "Surdas" },
  { t: "अँधेरे बंद कमरे", a: "मोहन राकेश", ts: "Andhere Band Kamre", as: "Mohan Rakesh" },
  { t: "वर्षा", a: "सुमित्रानंदन पंत", ts: "Varsha", as: "Sumitranandan Pant" },
  { t: "ग्राम्या", a: "सुमित्रानंदन पंत", ts: "Gramya", as: "Sumitranandan Pant" },
  { t: "युगवत", a: "सुमित्रानंदन पंत", ts: "Yugavat", as: "Sumitranandan Pant" },
  { t: "ज़ोहरा", a: "सूर्यकांत त्रिपाठी निराला", ts: "Zohra", as: "Suryakant Tripathi Nirala" },
  { t: "राम की शक्ति पूजा", a: "सूर्यकांत त्रिपाठी निराला", ts: "Ram Ki Shakti Puja", as: "Nirala" },
  { t: "बेला", a: "सूर्यकांत त्रिपाठी निराला", ts: "Bela", as: "Nirala" },
  { t: "फ़ैज़ की शायरी", a: "फ़ैज़ अहमद फ़ैज़", ts: "Faiz Ahmed Faiz", as: "Faiz" },
  { t: "दस्त-ए-सबा", a: "फ़ैज़ अहमद फ़ैज़", ts: "Dast-e-Saba", as: "Faiz" },
  { t: "नुक्ता-ए-नज़र", a: "फ़ैज़ अहमद फ़ैज़", ts: "Nukta-e-Nazar", as: "Faiz" },
  { t: "पंचतंत्र", a: "विष्णु शर्मा", ts: "Panchatantra", as: "Vishnu Sharma" },
  { t: "हितोपदेश", a: "नारायण", ts: "Hitopadesha", as: "Narayana" },
  { t: "व्यक्ति और विचार", a: "हजारी प्रसाद द्विवेदी", ts: "Vyakti Aur Vichar", as: "Hazari Prasad Dwivedi" },
  { t: "हिंदी कहानियाँ", a: "मुंशी प्रेमचंद", ts: "Hindi Kahaniyan Premchand", as: "Munshi Premchand" },
  { t: "इदगाह", a: "मुंशी प्रेमचंद", ts: "Idgah", as: "Munshi Premchand" },
  { t: "पूस की रात", a: "मुंशी प्रेमचंद", ts: "Poos Ki Raat", as: "Munshi Premchand" },
  { t: "बड़े घर की बेटी", a: "मुंशी प्रेमचंद", ts: "Bade Ghar Ki Beti", as: "Munshi Premchand" },
  { t: "नमक का दरोगा", a: "मुंशी प्रेमचंद", ts: "Namak Ka Daroga", as: "Munshi Premchand" },
  { t: "दो बैलों की कथा", a: "मुंशी प्रेमचंद", ts: "Do Bailon Ki Katha", as: "Munshi Premchand" },
  { t: "मंत्र", a: "मुंशी प्रेमचंद", ts: "Mantra Premchand", as: "Munshi Premchand" },
  { t: "वरदान", a: "मुंशी प्रेमचंद", ts: "Vardan", as: "Munshi Premchand" },
  { t: "त्यागी", a: "मुंशी प्रेमचंद", ts: "Tyagi", as: "Munshi Premchand" },
  { t: "प्रेमचंद की कहानियाँ", a: "मुंशी प्रेमचंद", ts: "Premchand Ki Kahaniyan", as: "Munshi Premchand" },
  { t: "हिंदी उपन्यास परिचय", a: "रामविलास शर्मा", ts: "Hindi Upanyas Parichay", as: "Ramvilas Sharma" },
  { t: "आधुनिक हिंदी कविता", a: "नामवर सिंह", ts: "Aadhunik Hindi Kavita", as: "Namvar Singh" },
  { t: "हिंदी काव्य का इतिहास", a: "आचार्य रामचंद्र शुक्ल", ts: "Hindi Kavya Ka Itihas", as: "Ramchandra Shukla" },
  { t: "शब्दों का शहर", a: "कृष्णा सोबती", ts: "Shabdon Ka Shehar", as: "Krishna Sobti" },
  { t: "दार से बिछुड़ी", a: "कृष्णा सोबती", ts: "Daar Se Bichhudi", as: "Krishna Sobti" },
  { t: "मित्रो मरजानी", a: "कृष्णा सोबती", ts: "Mitro Marjani", as: "Krishna Sobti" },
  { t: "आधुनिकता", a: "गजानन माधव मुक्तिबोध", ts: "Aadhunikta Muktibodh", as: "Gajanan Madhav Muktibodh" },
  { t: "ब्रह्मराक्षसी", a: "धूमिल", ts: "Brahmrakshasi", as: "Dhoomil" },
  { t: "जनशक्ति", a: "रामधारी सिंह दिनकर", ts: "Janashakti", as: "Ramdhari Singh Dinkar" }
];
