"""create wishlist tables

Revision ID: 7e112f6cb37a
Revises: 8d6ef3d58848
Create Date: 2026-04-06 14:57:45.511280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e112f6cb37a'
down_revision: Union[str, Sequence[str], None] = '8d6ef3d58848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_user_wishlist_book')
    )
    op.create_index(op.f('ix_wishlist_book_id'), 'wishlist', ['book_id'], unique=False)
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    op.alter_column('books', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2, asdecimal=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'rating',
               existing_type=sa.Float(precision=2, asdecimal=1),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_book_id'), table_name='wishlist')
    op.drop_table('wishlist')
    # ### end Alembic commands ###
