"""add rate limit counters

Revision ID: 8f857aedc488
Revises: cf9a266f508b
Create Date: 2026-08-19 13:08:24.349018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f857aedc488'
down_revision: Union[str, Sequence[str], None] = 'cf9a266f508b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    The books.rating REAL -> Float suggestion is stripped again; see
    8d6ef3d58848. Float(precision=2) maps to REAL in PostgreSQL so autogenerate
    proposes it forever.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_counters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('client_key', sa.String(length=128), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'client_key', 'window_start', name='uq_rate_limit_window')
    )
    op.create_index(op.f('ix_rate_limit_counters_window_start'), 'rate_limit_counters', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_counters_window_start'), table_name='rate_limit_counters')
    op.drop_table('rate_limit_counters')
    # ### end Alembic commands ###
