"""add order refund and stage timestamp columns

Revision ID: a3f27c9d1e84
Revises: 8f857aedc488
Create Date: 2026-08-19 15:52:10.118433

Two gaps, both about an order's history not being recorded anywhere.

Refunds: cancelling a paid order restored the stock and kept the money, because
there was nowhere to write a refund. The refund columns are kept separate from
the `payment_*` ones so a refunded order still shows what was originally charged.

Stage timestamps: `status` said where an order was but never since when, so the
customer's status timeline read `shipped_at` / `delivered_at` — fields that did
not exist — and every order showed a dash for every step after "placed".

Written by hand rather than autogenerated: these are nullable columns, and
autogenerate would drag in the recurring books.rating REAL -> Float false
positive (see 8d6ef3d58848) that already caused one duplicate-migration tangle.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f27c9d1e84'
down_revision: Union[str, Sequence[str], None] = '8f857aedc488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TIMESTAMP_COLUMNS = ('packed_at', 'shipped_at', 'delivered_at', 'cancelled_at')


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('refund_reference', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True))

    for name in _TIMESTAMP_COLUMNS:
        op.add_column('orders', sa.Column(name, sa.DateTime(timezone=True), nullable=True))

    # Existing rows have a status but no history. Backfilling from `created_at` is
    # the only honest option available — it is when we know the order existed —
    # and it beats a timeline of dashes for orders placed before this migration.
    op.execute("UPDATE orders SET cancelled_at = created_at WHERE status = 'cancelled'")
    op.execute("UPDATE orders SET shipped_at = created_at WHERE status IN ('shipped', 'delivered')")
    op.execute("UPDATE orders SET delivered_at = created_at WHERE status = 'delivered'")
    op.execute("UPDATE orders SET packed_at = created_at WHERE status IN ('packed', 'shipped', 'delivered')")


def downgrade() -> None:
    """Downgrade schema."""
    for name in reversed(_TIMESTAMP_COLUMNS):
        op.drop_column('orders', name)

    op.drop_column('orders', 'refund_amount')
    op.drop_column('orders', 'refund_reference')
    op.drop_column('orders', 'refunded_at')
