"""add books search vector and hot-path indexes

Revision ID: b7d4e1a92c56
Revises: a3f27c9d1e84
Create Date: 2026-08-19 16:41:52.774310

Search was `ILIKE '%term%'` across three columns: a leading wildcard, so no index
could be used and every search scanned the whole catalogue, with no ranking and no
tolerance for a typo.

`search_vector` is a generated column, so PostgreSQL maintains it — a trigger or
application-side update could fall out of step with the row it describes. The GIN
index on it serves ranked full-text search; the trigram indexes serve the
typo-tolerant fallback and make substring matching indexable at all.

The remaining indexes cover queries that were sorting after the fetch: a
customer's orders newest-first, category browse newest-first, the unread
notification badge, and the worker's job claim (partial, because the rows a
worker wants are the unfinished minority).

Written by hand rather than autogenerated: autogenerate does not emit
`postgresql_ops` for trigram indexes, and it would drag in the recurring
books.rating REAL -> Float false positive (see 8d6ef3d58848).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d4e1a92c56'
down_revision: Union[str, Sequence[str], None] = 'a3f27c9d1e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match `_SEARCH_EXPRESSION` in app/database/models/book.py. A difference
# would make the test schema (built with create_all) and a migrated database rank
# results differently, which is the kind of divergence nobody notices until a
# search behaves differently in production than it does in a test.
SEARCH_EXPRESSION = (
    "setweight(to_tsvector('english', coalesce(title, '')), 'A') || "
    "setweight(to_tsvector('english', coalesce(author, '')), 'B') || "
    "setweight(to_tsvector('english', coalesce(description, '')), 'C')"
)


def upgrade() -> None:
    """Upgrade schema."""
    # Required by the trigram indexes below. Fails loudly if the role cannot
    # create extensions, which is the correct outcome: a silently missing
    # extension would mean a silently missing fallback.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.execute(
        "ALTER TABLE books ADD COLUMN search_vector tsvector "
        f"GENERATED ALWAYS AS ({SEARCH_EXPRESSION}) STORED"
    )

    op.create_index(
        "ix_books_search_vector", "books", ["search_vector"], postgresql_using="gin"
    )
    op.create_index(
        "ix_books_title_trgm", "books", ["title"],
        postgresql_using="gin", postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_books_author_trgm", "books", ["author"],
        postgresql_using="gin", postgresql_ops={"author": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_books_category_created", "books", ["category_id", sa.text("created_at DESC")]
    )

    op.create_index(
        "ix_orders_user_created", "orders", ["user_id", sa.text("created_at DESC")]
    )
    op.create_index("ix_notifications_user_read", "notifications", ["user_id", "is_read"])
    op.create_index(
        "ix_jobs_pending_run_at", "jobs", ["run_at"],
        postgresql_where=sa.text("completed_at IS NULL"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_jobs_pending_run_at", table_name="jobs")
    op.drop_index("ix_notifications_user_read", table_name="notifications")
    op.drop_index("ix_orders_user_created", table_name="orders")

    op.drop_index("ix_books_category_created", table_name="books")
    op.drop_index("ix_books_author_trgm", table_name="books")
    op.drop_index("ix_books_title_trgm", table_name="books")
    op.drop_index("ix_books_search_vector", table_name="books")

    op.drop_column("books", "search_vector")

    # pg_trgm is deliberately left installed: dropping an extension other objects
    # may depend on is not this migration's business to decide.
