"""sync models with db

Revision ID: bb0605f838e6
Revises: c4e8b1a2d3f0
Create Date: 2026-04-06 12:31:39.396920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0605f838e6'
down_revision: Union[str, Sequence[str], None] = 'c4e8b1a2d3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Every change below is already made by an adjacent revision: `catalog_id`,
    `author` and `ix_books_catalog_id` by c4e8b1a2d3f0 (this revision's parent),
    and the `rating` type change by 8d6ef3d58848. This revision was autogenerated
    against a database where those were not yet stamped, so running it verbatim
    fails on a fresh database with DuplicateColumn. Guard each op so the chain
    upgrades from scratch and stays a no-op where the change already landed.
    """
    inspector = sa.inspect(op.get_bind())
    columns = {col["name"] for col in inspector.get_columns("books")}
    indexes = {idx["name"] for idx in inspector.get_indexes("books")}

    if "catalog_id" not in columns:
        op.add_column('books', sa.Column('catalog_id', sa.String(length=64), nullable=True))
    if "author" not in columns:
        op.add_column('books', sa.Column('author', sa.String(length=255), nullable=True))
    op.alter_column('books', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2, asdecimal=1),
               existing_nullable=False)
    if op.f('ix_books_catalog_id') not in indexes:
        op.create_index(op.f('ix_books_catalog_id'), 'books', ['catalog_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema.

    Only the `rating` type is reverted here; the columns and index this revision
    guards are owned by c4e8b1a2d3f0, which drops them in its own downgrade.
    """
    op.alter_column('books', 'rating',
               existing_type=sa.Float(precision=2, asdecimal=1),
               type_=sa.REAL(),
               existing_nullable=False)
