"""sync models with db

Revision ID: bb0605f838e6
Revises: c4e8b1a2d3f0
Create Date: 2026-04-06 12:31:39.396920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0605f838e6'
down_revision: Union[str, Sequence[str], None] = 'c4e8b1a2d3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('catalog_id', sa.String(length=64), nullable=True))
    op.add_column('books', sa.Column('author', sa.String(length=255), nullable=True))
    op.alter_column('books', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2, asdecimal=1),
               existing_nullable=False)
    op.create_index(op.f('ix_books_catalog_id'), 'books', ['catalog_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_catalog_id'), table_name='books')
    op.alter_column('books', 'rating',
               existing_type=sa.Float(precision=2, asdecimal=1),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('books', 'author')
    op.drop_column('books', 'catalog_id')
    # ### end Alembic commands ###
