"""index the six foreign keys that had none

Revision ID: e7f2c94a1b38
Revises: d4e8b1c73a05
Create Date: 2026-09-15 11:40:00.000000

PostgreSQL validates a parent `DELETE` by checking the child table for rows that
reference it, and with no index on the referencing column that check is a
sequential scan. Nothing indexes a foreign key for you — `ForeignKey(...)` in the
model creates the constraint, not an index.

Found by asking the database rather than reading the models:

    select c.conrelid::regclass, a.attname from pg_constraint c
    join pg_attribute a on a.attrelid = c.conrelid and a.attnum = any(c.conkey)
    where c.contype = 'f' and not exists (
      select 1 from pg_index i
      where i.indrelid = c.conrelid and a.attnum = i.indkey[0]);

`cart_items.book_id` is the one that bites first: it is read on every cart render
(the cart response embeds each line's book) and scanned whenever a book is
removed from the catalogue.

Written by hand rather than autogenerated, for the reason given in d4e8b1c73a05:
autogenerate drags in the recurring `books.rating` REAL -> Float false positive.

Plain `CREATE INDEX`, not `CONCURRENTLY`. These tables are small today and a
concurrent build cannot run inside a transaction, which is what an Alembic
migration is. Building them now is precisely what avoids needing the concurrent
form later.
"""
from typing import Sequence, Union

from alembic import op

revision: str = "e7f2c94a1b38"
down_revision: Union[str, None] = "d4e8b1c73a05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (index name, table, column)
INDEXES = [
    ("ix_cart_items_book_id", "cart_items", "book_id"),
    ("ix_buyback_requests_book_id", "buyback_requests", "book_id"),
    ("ix_books_source_buyback_id", "books", "source_buyback_id"),
    ("ix_wallet_transactions_order_id", "wallet_transactions", "order_id"),
    ("ix_wallet_transactions_buyback_request_id", "wallet_transactions", "buyback_request_id"),
    ("ix_idempotency_keys_order_id", "idempotency_keys", "order_id"),
]


def upgrade() -> None:
    for name, table, column in INDEXES:
        op.create_index(name, table, [column])


def downgrade() -> None:
    for name, table, _column in reversed(INDEXES):
        op.drop_index(name, table_name=table)
